# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jrtplib-static' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jrtplib-static

end

target 'jrtplib-static-OSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jrtplib-static-OSX

end

target 'Жабир' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'ObjectiveDropboxOfficial'
pod 'TPCircularBuffer'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SAMKeychain'
pod 'CWStatusBarNotification', '~> 2.3.5'
pod 'MWPhotoBrowser', :podspec =>'https://raw.githubusercontent.com/moinku07/MWPhotoBrowser/master/MWPhotoBrowser.podspec'
pod 'SDWebImage', '~> 4.3.3'
pod 'Block-KVO', :git => 'https://github.com/Tricertops/Block-KVO.git'

  # Pods for Жабир

  target 'Жабир Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Жабир-OSX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #  use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'ObjectiveDropboxOfficial'
pod 'SAMKeychain'
pod 'TPCircularBuffer'
pod 'Sparkle'


  # Pods for Жабир-OSX

  target 'Жабир-OSXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
